---
# file: behave_4_noops.yml
# These definitions are for testing out configurations for
# the use of Docker and Hyperledger.

- name: Ensure NOOPS 4 folder "{{fabriclauncher_behave_4_noops_dir}} exists.
  file: path={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}/ 
        owner={{user}} group={{group}} mode=755
        recurse=yes
        state=directory
  register: out
  when: is_linux
          
- name: Copy hyperledger compose-defaults.yml
  template: src={{fabriclauncher_behave_4_noops_dir}}/compose-defaults.yml.j2
        dest={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}/compose-defaults.yml
        owner={{user}} group={{group}} mode=644
  when: is_linux

- name: Copy hyperledger docker-compose-4-consensus-base.yml
  template: src={{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-base.yml.j2
        dest={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-base.yml
        owner={{user}} group={{group}} mode=644
  when: is_linux

- name: Copy hyperledger docker-compose-4-consensus-noops.yml
  template: src={{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-noops.yml.j2
        dest={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-noops.yml
        owner={{user}} group={{group}} mode=644
  when: is_linux

- name: Copy hyperledger docker-compose-4-consensus-classic.yml
  template: src={{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-classic.yml.j2
        dest={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}/docker-compose-4-consensus-classic.yml
        owner={{user}} group={{group}} mode=644
  when: is_linux

- name: Launch Hyperledger Devnet (NOOPS) 
  docker_service:
      project_src={{fabriclauncher_config_dir}}/{{fabriclauncher_behave_4_noops_dir}}
      files=docker-compose-4-consensus-noops.yml
  register: output
  when: is_linux

