---
# file: configurable.yml
# These tasks are for configuring and launching a customized instance
# of Hyperledger Fabric on Docker using Docker Swarm Mode.

- name: Ensure the folder "{{fabriclauncher_config_dir}}/{{fabriclauncher_configurable_dir}}/" exists.
  file: path={{fabriclauncher_config_dir}}/{{fabriclauncher_configurable_dir}}/ 
        owner={{user}} group={{group}} mode=755
        state=directory
  when: is_linux
  tags: [fabric]
    
- name: Generate Docker Compose file fabric.yml and install it in "{{fabriclauncher_config_dir}}/{{fabriclauncher_configurable_dir}}/fabric-base.yml"
  template: src={{fabriclauncher_configurable_dir}}/fabric.yml.j2
        dest={{fabriclauncher_config_dir}}/{{fabriclauncher_configurable_dir}}/fabric.yml
        owner={{user}} group={{group}} mode=644
  when: is_linux
  tags: [fabric]

# See: https://github.com/ansible/ansible-modules-core/issues/4607        
- name: Used the generated Docker Compose file to launch Hyperledger Fabric on the swarm with ({{fabriclauncher_num_validating_peers}} validating peers).
  command: chdir={{fabriclauncher_config_dir}}/{{fabriclauncher_configurable_dir}}
           docker stack deploy --compose-file fabric.yml hyperledger
  when: is_linux
  tags: [fabric]
  
