---
# file: consulhosts.yml
# These definitions are for machines that serve as hosts for consul.
# See: https://www.consul.io/
# See: https://hub.docker.com/_/consul/

- hosts: consulclients
  become: true
  pre_tasks:
      - assert:
         that: "ansible_version.major >= {{hl_minimum_ansible_version_major}} and ansible_version.minor >= {{hl_minimum_ansible_version_minor}}"
  roles:
    - {role: dockerhost,
              user: "{{ lookup('env', 'USER') }}"
      }
    - {role: consulhost
      }
