---
# file: fabriclaunchers.yml
# These definitions are for hosts that launch instances of the Hyperledger 
# Fabric Network using Docker and Docker Compose.
# https://www.docker.io/
# For this playbook, also see: http://docs.docker.io/en/latest/installation/ubuntulinux/

- hosts: fabriclauncher
  gather_facts: true
  become: true
  vars:
  
    - consortium_name: "KeojaConsortium"
    - orderer_org_name: "keoja"
    - peer_orgname: "{{orderer_org_name}}"
    - num_peers: 2
    - domain:  "keoja.com"
    - dockertag: "x86_64-1.0.0-rc1"
    # Variables for crypto-config.yaml.j2
    - fabric_crypto_config: {ordererorgs: [ 
                                { name: "{{orderer_org_name}}", domain: "{{domain}}", 
                                  #specs: [ { hostname: "zip", commonname: "zap"} ],
                                  template: { count: 1}
                                }
                               ],
                             peerorgs: [ 
                                { name: "{{peer_orgname}}", domain: "{{domain}}",
                                  #specs: [ { hostname: "zip", commonname: "zap"} ],
                                  template: { count: "{{num_peers}}" }
                                }
                               ]
                            }
    
    # Variables for configtx.yaml.j2
    - fabric_profiles: [ {
                      name: "OneOrgGenesis",
                      orderer: { defaultstag: "OrdererDefaults", organizations: ["{{orderer_org_name}}"]},
                      ordererorg: "{{orderer_org_name}}",
                      consortiums: [{name: "{{consortium_name}}", organizations : ["{{orderer_org_name}}"] }],
                  },
                  {
                     name: "OneOrgChannel",
                     consortium: "{{consortium_name}}",
                     application: { tag: "ApplicationDefaults", organizations: ["{{orderer_org_name}}"]},
                  }
                ]
                
    - fabric_organizations: [
                     {
                       tag : "OrderOrg",
                       name : "{{orderer_org_name}}",
                       id : "OrderOrgMSP",
                       msp_dir : "crypto-config/ordererOrganizations/{{domain}}/msp",
                     },
                     {
                       tag: "{{orderer_org_name}}",
                       name: "{{orderer_org_name}}MSP",
                       id: "{{orderer_org_name}}MSP",
                       msp_dir: "crypto-config/peerOrganizations/{{domain}}/msp",
                       anchorpeers : [{ "host" : "peer0.{{domain}}", "port" : "7051"}]
                     }
                ]
    - fabric_ordererdefaults: {
                     tag: "OrdererDefaults",
                     type: "solo",
                     addresses: ["orderer.{{domain}}:7050"],
                     batch: { timeout: "2s", maxmsgcount: "10", maxbytes: "99 MB", preferredmaxbytes: "512 KB"},
                     maxchannels: 0,
                     kafka: {"brokers" : [ "127.0.0.1:9092"]},
                     organizations: []
               }
    - fabric_applicationdefaults: {
                     tag: "ApplicationDefaults"
      }
    # Variables for fabric-docker-compose.yml.j2
    - fabric_compose: {
                     ca: {
                       domain: "{{domain}}",
                       image: "hyperledger/fabric-ca:{{dockertag}}",
                       env: {
                         ca_server_tls_enabled: "true",
                       },
                       ports: ["7054:7054"],
                       command: "sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.{{domain}}-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY -b admin:adminpw -d'",
                       volumes: ["./fabricca/tlsOrg1:/etc/hyperledger/fabric-ca-server"]
                     },
                     orderer: {
                       genesisprofile: "OneOrgGenesis",
                       name: "orderer",
                       domain: "{{domain}}",
                       image: "hyperledger/fabric-orderer:{{dockertag}}",
                       ports: ["7050:7050"],
                       workingdir: "/opt/gopath/src/github.com/hyperledger/fabric",
                       command: "orderer",
                     },
                     peers: { 
                       image: "hyperledger/fabric-peer:{{dockertag}}",
                       command: "peer node start --peer-defaultchain=false",
                       ports: {
                           p1: 7051,
                           p2: 7053,
                           hostbase: 7055
                       },
                       organizations: [
                        {
                          numpeers: "{{num_peers}}",
                          peername: "peer",
                          domain: "{{domain}}",
                          env: {
                            localmspid: "Org1MSP",
                            vm_endpoint: "unix:///host/var/run/docker.sock",
                            vm_docker_hostconfig_networkmode: "fixturesv1_default",
                            logging_level: "INFO",
                            tls_enabled: "true",
                            endorser_enabled: "true",
                            gossip_useleaderelection: "true",
                            gossip_orgleader: "false",
                            gossip_skiphandshake: "true",
                            gossip_profile_enabled: "true",
                          },
                          workingdir: "/opt/gopath/src/github.com/hyperledger/fabric",
                        }
                       ]
                     }
       }
    
  pre_tasks:
      - assert:
         that: "ansible_version.major >= {{hl_minimum_ansible_version_major}} and ansible_version.minor >= {{hl_minimum_ansible_version_minor}}"
  roles:
    - { role: fabriclauncher,
          user: "{{ansible_user}}",
          group: "{{'staff' if is_macosx|bool else ansible_user}}",
          cryptoconfig: "{{fabric_crypto_config}}",
          profiles: "{{fabric_profiles}}",
          organizations: "{{fabric_organizations}}",
          ordererdefaults: "{{fabric_ordererdefaults}}",
          applicationdefaults: "{{fabric_applicationdefaults}}"
      }
